[package]
name = "galaxy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_prototype_lyon.workspace = true
bevy_asset_loader.workspace = true
engine_core = { path = "../engine_core" }
space = { path = "../space" }