[package]
name = "test_space"
version = "0.1.0"
edition = "2021"

[dependencies]
engine_core = { path = "../engine_core" }
bevy = "0.14.2"

[dev-dependencies]
bevy-inspector-egui.workspace = true


[features]
default = ["f32"]
f32 = []
f64 = []