[package]
name = "core_pack_objects"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy_mod_scripting.workspace = true
serde.workspace = true
bevy.workspace  = true

[dev-dependencies]
bevy-inspector-egui.workspace = true
