[package]
name = "engine"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy_asset_loader.workspace = true
engine_core     = { path = "../engine_core" }
space           = { path = "../space"}
galaxy = { path = "../galaxies" }
utils = { path = "../utils" }
bevy.workspace  = true





